version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - ${DB_DOCKER_PORT}
    volumes:
      - pdb14:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-avenger:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_DOCKER_PORT}
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

volumes:
  pdb14:
networks:
  postgres-compose-network:
    driver: bridge