services:
  postgres:
    container_name: avengers_api_pg
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=avengers'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    volumes:
      - 'avengers_api_pg_data:/postgresql'

volumes:
  avengers_api_pg_data: