spring:
  application:
    name: avengers-api
    version: 1.0.0
    author: soupaulodev
    group: br.com.soupaulodev
  config:
#    spring:
#      profiles:
#        group: br.com.soupaulodev
#          <group>: dev
    use-legacy-processing: true
  profiles:
    active: dev
  jmx:
    enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: true
    properties:
      hibernate:
        time_zone: UTC
        generate_statistics: false
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: avengers-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: avengers-scheduler-
      pool:
        size: 2
  output:
    ansi:
      console-available: true

server:
  port: 9090
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /avengers